name: Daily Clean Twitter Robot User

on:
  schedule:
    - cron: 15 10 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup ENV
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

        run: |
          cd server
          yarn install
          yarn build

      - name: Start Job
        run: |
          cd server
          node dist/job.js